#!/usr/bin/env bash
set -x

source .env

this=`pwd`
mkdir $this/doc $this/src $this/examples

temp=`mktemp -d`
pushd $temp

git clone https://github.com/frameorc/dom.git
cd dom
cp -a ./src/{dom,snabb}.js $this/src
cp -a ./examples/* $this/examples
cp -a ./README.md $this/doc/dom.md
cp -a ./LICENSE $this/
cd ..

git clone https://github.com/frameorc/router.git
cd router
cp ./router.js $this/src
cp ./README.md $this/doc/router.md
cp -a ./examples/* $this/examples
cd ..

git clone https://github.com/frameorc/flex.git
cd flex
cp ./flex.css $this/src
cp ./flex.css $this/doc/flex.css
cp ./index.html $this/doc/flex.html
cd ..

git clone https://github.com/frameorc/state.git
cd state
cp ./state.js $this/src
cp ./state.fs.js $this/src
cp ./state.ls.js $this/src
cp ./README.md $this/doc/state.md
sed s%./state.ls.js%../src/state.ls.min.js% ./demo.html > $this/examples/state-demo.html
cd ..


popd
rm -rf $temp

bun build ./src/dom.js --outfile ./src/dom.min.js --minify
bun build ./src/router.js --outfile ./src/router.min.js --minify
bun build ./src/state.ls.js --outfile ./src/state.ls.min.js --minify
bun build ./src/state.fs.js --outfile ./src/state.fs.min.js --minify

git add .
git commit -m "Published at `date -u +'%F %T'`"

